spring.jpa.database: "POSTGRESQL-DEV-NEW"
spring.datasource.platform:  "postgres"
spring.datasource.url: "jdbc:postgresql://localhost:5432/company"
spring.datasource.username: "postgres"
spring.datasource.password: "root"
spring.jpa.show-sql: "true"
spring.jpa.generate-ddl: "true"
spring.jpa.hibernate.ddl-auto: "create-drop"
spring.database.driverClassName: "org.postgresql.Driver"
spring.jpa.properties.hibernate.dialect: "org.hibernate.dialect.PostgreSQLDialect"
spring.datasource.hikari.connectionTimeout: "20000"
spring.datasource.hikari.maximumPoolSize: "5"
spring.jpa.properties.hibernate.temp.use_jdbc_metadata_defaults: "false"
